image: debian/trixie
packages:
  - jq
  - rustup
  - binutils-arm-none-eabi
  - rhash
tasks:
  - prep: |
      rustup toolchain install stable
      rustup target install thumbv8m.main-none-eabihf
      git clone https://git.sr.ht/~scwork/mcaux-ct m
      cargo install --path m/cargo-utility-section cargo-utility-section
  - build: |
      PATH=$PATH:. DFU0=http://example.org/DFU/ AP0=SSID PW0=password make -C m/mcaux
  - archive: |
      git clone git@git.sr.ht:~scwork/archive a
      mkdir -p a/mcaux
      cp m/b/archive/* a/mcaux
      (cd a
      && git add *
      && git commit -m "sr.ht ${JOB_ID} ${JOB_URL} ${BUILD_SUBMITTER} ${BUILD_REASON}"
      && git push)
