[package]
edition = "2024"
name = "mcaux-rp2040"
version = "0.2.0"
authors = ["Steve Work <steve@work.renlabs.com>"]
license = "MIT OR Apache-2.0"

publish = false

[[bin]]
name = "mcaux-rp2040"
test = false
bench = false

[dependencies]
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
cyw43 = { version = "0.6.0", features = ["defmt", "firmware-logs"] }
cyw43-pio = { version = "0.9.0", features = ["defmt"] }

defmt = "1.0.1"
cortex-m-rt = "0.7.5"
mcaux = { version="0.1.0", path="../mcaux", features = ["rp2040"]}
static_cell = "2.1.1"
embassy-rp = { version = "0.9.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "binary-info"] }
defmt-rtt = "1.1.0"


