[package]
name = "momentary"
version = "0.1.0"
edition = "2024"

[features]
not-no-std = []
embassy = ["dep:embassy-time"]
wasm = ["dep:web-time"]

[dependencies]
embassy-time = { version = "0.5.0", optional = true, path = "/home/steve/Code/Github/embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime"] }
web-time = { version = "1.1.0", optional = true }
