
name: CI rp235x

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
      - run: cargo check --features rp235xa --target thumbv8m.main-none-eabihf

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
          components: clippy
      - run: cargo clippy --features rp235xa -- -D warnings

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-app
    steps:
      - uses: actions/checkout@master
      - uses: actions-rust-lang/setup-rust-toolchain@v1.0.1
        with:
          toolchain: stable
          target: thumbv8m.main-none-eabihf
          override: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y binutils-arm-none-eabi
      - run: mkdir -p _site/dfu/pico2w/latest
      - run: cargo build --features rp235xa --release
