on: [push, pull_request, workflow_dispatch]

name: CI rp235x

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-rp235x
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
      - run: ln -s memory.x-APP memory.x
      - run: cargo check --all-features --target thumbv8m.main-none-eabihf

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-rp235x
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
          components: rustfmt
      - run: ln -s memory.x-APP memory.x
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-rp235x
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv8m.main-none-eabihf
          components: clippy
      - run: ln -s memory.x-APP memory.x
      - run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcaux-rp235x
    steps:
      - uses: actions/checkout@master
      - uses: actions-rust-lang/setup-rust-toolchain@v1.0.1
        with:
          toolchain: stable
          target: thumbv8m.main-none-eabihf
          override: true
      - run: ln -s memory.x-APP memory.x
      - run: cargo build --verbose --release

